const API_BASE_URL = "http://localhost:5555";
const NANOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NANOSECONDS_PY;
const MILLISECONDS_PY = 1000 * MICROSECONDS_PY;
const MILLISECONDS_JS = 1;
const SECONDS_JS = 1000 * MILLISECONDS_JS;
const POLL_INTERVAL = SECONDS_JS * 10;
// export { API_BASE_URL: 'url' };
export { API_BASE_URL, MILLISECONDS_PY, POLL_INTERVAL };
