NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS
MINE_RATE_SEC = 2
MINE_RATE = MINE_RATE_SEC * SECONDS

INIT_DIFFICULTY = 8

STARTING_BALANCE = 1000

ROOT_PORT = 5555

MINING_REWARD = 50
MINING_REWARD_INPUT = {"address": "*--official-mining-reward--*"}
